### ISSUE TITLE
/lib files not being compiled

### ISSUE THREAD

**Issue by seanjsavage** [synox/spark-transport-display#1]
Thanks for the great project.

In November I worked on some of this with my Spark Core and it compiled fine.  But now when I try to compile the same code, the Spark compiler doesn't seem to recognize any files under /lib.  (It breaks with Adafruit_CharacterOLED.h by default, but if I move that file out of /lib to the main project directory, it accepts Adafruit_CharacterOLED.h but breaks with the same error message for the next file under /lib. )

Relevant error text:

```
Errors
In file included from Transport.cpp:1:0:
Transport.h:4:36: fatal error: Adafruit_CharacterOLED.h: No such file or directory
 #include "Adafruit_CharacterOLED.h"
                                    ^
compilation terminated.
make: *** [Transport.o] Error 1

Compile failed -  compile failed
```

Thanks.

**Comment by synox** [comment]
how do you compile, which version? 
-spark cli
-spark dev ide

for me it works with the spark cli on osx 10.10

**Comment by seanjsavage** [comment]
Spark CLI on OSX 10.10.1.  Current version of Spark CLI – it's the latest version after upgrading (npm update -g spark-cli) so I assume that's spark-cli 0.4.93 (not sure where to summon v number but that's what's listed on Github).  Everything I've been doing has been on CLI, not Web IDE.

**Comment by seanjsavage** [comment]
Have you upgraded your CLI recently?  Someone else said they're having the same issue with a different project and it appeared after upgrading Spark CLI:
http://community.spark.io/t/subdirectories-not-compiling-in-cli/9283

**Comment by synox** [comment]
with spark-cli 0.4.4 I did not have any Problem.  now after upgrading to 0.4.93 i have the same issue. 

Lets do the discussion in http://community.spark.io/t/subdirectories-not-compiling-in-cli/9283

**Comment by seanjsavage** [comment]
Hi there

After I revert to spark-cli v 0.4.5, the /lib problem goes away. But I'm getting a different compile error with spark-transport-display that I didn't get back in November. (Pasted below.)

Are you experiencing that too? (Not sure whether to post this on Spark's boards or your Github, as I'm trying to diagnose which bits of this if any involve Transport-Display updates, vs. CLI updates... Vs. maybe something in my environment.)

Thanks

Sean

```
Transport.cpp:52:6: error: prototype for 'void Transport::init(Adafruit_CharacterOLED*, String, String, HttpClient*)' does not match any in class 'Transport'
 void Transport::init (Adafruit_CharacterOLED *lcd, String from, String to, HttpClient* client) {
      ^
In file included from Transport.cpp:1:0:
Transport.h:17:10: error: candidate is: void Transport::init(String, String, HttpClient*)
     void init(String from, String to, HttpClient* client);
          ^
Transport.cpp: In member function 'bool Transport::displayDepartures(int, int)':
Transport.cpp:231:4: error: 'lcd' was not declared in this scope
    lcd->setCursor(rowLength-time.length(),row); //
    ^
make: *** [Transport.o] Error 1

Compile failed -  compile failed
```

**Comment by synox** [comment]
tell me how to downgrade spark-cli, and I'll give it a try. 

PS: if everything is in one dir as in [branch test_nosubdir](https://github.com/synox/spark-transport-display/tree/test_nosubdir/firmware) then it works, but I don't like that.

**Comment by seanjsavage** [comment]
Run:

npm install -g spark-cli@0.4.5

(or replace 0.4.5 with whatever version you want)

**Comment by synox** [comment]
with version 0.4.5 and "cd firmware" and "spark compile ." it returns a valid firmware binary for me. (osx 10.10.1 (14B25) )

**Comment by seanjsavage** [comment]
Bizarro.  Only difference is that I compiled from the directory above:
"spark compile firmware."  And it spawned the errors I posted.

Hmm.. I'm sure that compiling from within the folder wouldn't make that
difference, but I will try it when I get home.  Assuming that's not it...
what else could be different?  Are you running the latest versions of
Yosemite and Node.js?  I am (don't have v #'s handy as I'm not on my
machine at the moment).

Anyway, you've eliminated Spark CLI as the potential problem so thanks.

Sean

**Comment by synox** [comment]
no difference from parent folder. 

my node and libs might be old, I didn't update them. compare the version output while downgrading, maybe we have a difference. 

```
# node  --version
 v0.10.32

# npm install -g spark-cli@0.4.5
-
> serialport@1.4.5 install /usr/local/lib/node_modules/spark-cli/node_modules/serialport
> node-pre-gyp install --fallback-to-build

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/serialport/src/serialport.o
  CXX(target) Release/obj.target/serialport/src/serialport_unix.o
  CXX(target) Release/obj.target/serialport/src/serialport_poller.o
  SOLINK_MODULE(target) Release/serialport.node
  SOLINK_MODULE(target) Release/serialport.node: Finished
  COPY /usr/local/lib/node_modules/spark-cli/node_modules/serialport/build/serialport/v1.4.5/Release/node-v11-darwin-x64/serialport.node
  TOUCH Release/obj.target/action_after_build.stamp
/usr/local/bin/spark -> /usr/local/lib/node_modules/spark-cli/bin/spark.js
spark-cli@0.4.5 /usr/local/lib/node_modules/spark-cli
├── xtend@4.0.0
├── when@3.6.4
├── hogan.js@2.0.0
├── moment@2.9.0
├── request@2.51.0 (caseless@0.8.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.5.0, tunnel-agent@0.4.0, node-uuid@1.4.2, qs@2.3.3, mime-types@1.0.2, combined-stream@0.0.7, http-signature@0.10.1, bl@0.9.3, tough-cookie@0.12.1, form-data@0.2.0, hawk@1.1.1)
└── serialport@1.4.5 (bindings@1.2.1, sf@0.1.7, async@0.9.0, nan@1.3.0, optimist@0.6.1)
```

**Comment by seanjsavage** [comment]
Hmm I have a later version of node:

```
Seans-MacBook-Pro-2:spark-transport-display-master seansavage$ node  --version
v0.10.33
Seans-MacBook-Pro-2:spark-transport-display-master seansavage$ sudo npm install -g spark-cli@0.4.5
Password:
-
> serialport@1.4.5 install /usr/local/lib/node_modules/spark-cli/node_modules/serialport
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/seansavage/.node-gyp/0.10.33"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/spark-cli/node_modules/serialport/.node-gyp"
  CXX(target) Release/obj.target/serialport/src/serialport.o
  CXX(target) Release/obj.target/serialport/src/serialport_unix.o
  CXX(target) Release/obj.target/serialport/src/serialport_poller.o
  SOLINK_MODULE(target) Release/serialport.node
  SOLINK_MODULE(target) Release/serialport.node: Finished
  COPY /usr/local/lib/node_modules/spark-cli/node_modules/serialport/build/serialport/v1.4.5/Release/node-v11-darwin-x64/serialport.node
  TOUCH Release/obj.target/action_after_build.stamp
/usr/local/bin/spark -> /usr/local/lib/node_modules/spark-cli/bin/spark.js
spark-cli@0.4.5 /usr/local/lib/node_modules/spark-cli
├── xtend@4.0.0
├── when@3.6.4
├── hogan.js@2.0.0
├── moment@2.9.0
├── request@2.51.0 (caseless@0.8.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.5.0, tunnel-agent@0.4.0, node-uuid@1.4.2, qs@2.3.3, mime-types@1.0.2, combined-stream@0.0.7, tough-cookie@0.12.1, http-signature@0.10.1, hawk@1.1.1, bl@0.9.3, form-data@0.2.0)
└── serialport@1.4.5 (bindings@1.2.1, sf@0.1.7, async@0.9.0, nan@1.3.0, optimist@0.6.1)
```

**Comment by synox** [comment]
I don't know what else to try. let's wait for a fixed version of spark-cli.
